"""Helper script: generates round_simulation.ipynb"""
import json
from pathlib import Path

cells = []

def md(src):
    return {"cell_type": "markdown", "metadata": {}, "source": src, "outputs": []}

def code(src):
    return {"cell_type": "code", "metadata": {}, "source": src, "outputs": [], "execution_count": None}


cells.append(md(
    "# Arya Phones — Round-by-Round Customer Simulation\n\n"
    "MNL demand computed **per segment per round**. Tracks how supplier selection, "
    "price, and delta changes affect each customer group over time.\n\n"
    "## Scenarios\n"
    "1. **Price War** — 3 teams, same set [P], price competition over 6 rounds\n"
    "2. **Selection Shock** — TeamA upgrades from [P] to [P,O,N] in round 4\n"
    "3. **Delta Sweep** — same teams/prices, delta rises 0.02→0.5 each round\n"
    "4. **Tournament** — 4 teams, 8 rounds, Beta distribution shifts at round 5"
))

cells.append(code(
    "import sys, warnings\n"
    "from pathlib import Path\n"
    "import pandas as pd\n"
    "import numpy as np\n"
    "import matplotlib.pyplot as plt\n"
    "\n"
    "PROJECT_ROOT = Path('../..').resolve()\n"
    "if str(PROJECT_ROOT) not in sys.path:\n"
    "    sys.path.insert(0, str(PROJECT_ROOT))\n"
    "\n"
    "warnings.filterwarnings('ignore')\n"
    "\n"
    "from server.app.service import get_tables\n"
    "from server.app.settings import GAME_SETTINGS\n"
    "from server.app.beta_density import BetaDensity\n"
    "from server.app.mnl_market import BuyerProfile, run_mnl_market\n"
    "from server.app.customer_segment import CustomerSegment\n"
    "\n"
    "suppliers_df, users_df = get_tables()\n"
    "N = len(users_df)\n"
    "print(f'Suppliers: {len(suppliers_df)}  |  Segments: {N}')\n"
    "PALETTE = ['#2563eb','#dc2626','#059669','#7c3aed','#d97706','#0891b2','#be123c','#65a30d']\n"
))

cells.append(code(
    "# ─── Helpers ─────────────────────────────────────────────────────────────\n"
    "\n"
    "def avg_attrs(picks):\n"
    "    sel = suppliers_df[suppliers_df['supplier_id'].isin(picks)]\n"
    "    if sel.empty: return {}\n"
    "    return {c: float(sel[c].mean()) for c in\n"
    "            ['env_risk','social_risk','cost_score','strategic','improvement','low_quality']}\n"
    "\n"
    "def is_feasible(picks):\n"
    "    a = avg_attrs(picks)\n"
    "    return (len(picks) > 0\n"
    "            and a.get('env_risk', 99) <= GAME_SETTINGS.env_cap + 1e-9\n"
    "            and a.get('social_risk', 99) <= GAME_SETTINGS.social_cap + 1e-9)\n"
    "\n"
    "def make_segments(alpha=3.0, beta=3.0):\n"
    "    bd = BetaDensity(alpha=max(0.01, alpha), beta=max(0.01, beta))\n"
    "    us = users_df.sort_values('w_cost').reset_index(drop=True)\n"
    "    return [\n"
    "        CustomerSegment(\n"
    "            segment_id=str(row['user_id']),\n"
    "            density=float(bd.density_at((i + 0.5) / N)),\n"
    "            w_env=float(row.get('w_env', 0)),\n"
    "            w_social=float(row.get('w_social', 0)),\n"
    "            w_cost=float(row.get('w_cost', 1)),\n"
    "            w_strategic=float(row.get('w_strategic', 0)),\n"
    "            w_improvement=float(row.get('w_improvement', 0)),\n"
    "            w_low_quality=float(row.get('w_low_quality', 0)),\n"
    "        )\n"
    "        for i, (_, row) in enumerate(us.iterrows())\n"
    "    ]\n"
    "\n"
    "def buyer_profile(name, picks, price):\n"
    "    a = avg_attrs(picks)\n"
    "    return BuyerProfile(\n"
    "        team_name=name, price_per_user=float(price),\n"
    "        avg_env=a.get('env_risk', 0), avg_social=a.get('social_risk', 0),\n"
    "        avg_strategic=a.get('strategic', 0), avg_improvement=a.get('improvement', 0),\n"
    "        avg_low_quality=a.get('low_quality', 0),\n"
    "    )\n"
    "\n"
    "def run_round(team_specs, alpha=3.0, beta=3.0, delta=0.1, u_outside=-3.0):\n"
    "    \"\"\"Returns (round_df, segment_df). One row per team / per (team x segment).\"\"\"\n"
    "    segs = make_segments(alpha, beta)\n"
    "    profiles = [buyer_profile(name, picks, price) for name, picks, price in team_specs]\n"
    "    result = run_mnl_market(profiles, segs, delta=delta, u_outside=u_outside)\n"
    "\n"
    "    us_s = users_df.sort_values('w_cost').reset_index(drop=True)\n"
    "    seg_idx  = {str(r['user_id']): i+1    for i,(_, r) in enumerate(us_s.iterrows())}\n"
    "    seg_wc   = {str(r['user_id']): float(r['w_cost']) for _, r in us_s.iterrows()}\n"
    "    total_d  = sum(s.density for s in segs)\n"
    "\n"
    "    team_rows = []\n"
    "    for name, picks, price in team_specs:\n"
    "        a  = avg_attrs(picks)\n"
    "        br = result.buyer_results.get(name)\n"
    "        demand = br.total_demand if br else 0.0\n"
    "        eff    = demand * N\n"
    "        margin = price - GAME_SETTINGS.cost_scale * a.get('cost_score', 0)\n"
    "        team_rows.append({\n"
    "            'team': name, 'picks': ','.join(picks), 'feasible': is_feasible(picks),\n"
    "            'price': price, 'delta': delta, 'alpha': alpha, 'beta': beta,\n"
    "            'demand_share_pct':  round(demand * 100, 2),\n"
    "            'effective_users':   round(eff, 3),\n"
    "            'unit_margin':       round(margin, 2),\n"
    "            'realized_profit':   round(eff * margin, 2),\n"
    "            'realized_utility':  round((br.realized_utility * N) if br else 0.0, 3),\n"
    "            'avg_env':   round(a.get('env_risk', 0), 3),\n"
    "            'avg_social':round(a.get('social_risk', 0), 3),\n"
    "            'avg_cost':  round(a.get('cost_score', 0), 3),\n"
    "        })\n"
    "\n"
    "    seg_rows = []\n"
    "    for alloc in result.segment_allocations:\n"
    "        sid   = alloc.segment_id\n"
    "        norm  = alloc.density / total_d\n"
    "        for name, picks, price in team_specs:\n"
    "            a      = avg_attrs(picks)\n"
    "            share  = alloc.shares.get(name, 0.0)\n"
    "            eff_s  = share * norm * N\n"
    "            margin = price - GAME_SETTINGS.cost_scale * a.get('cost_score', 0)\n"
    "            seg_rows.append({\n"
    "                'team': name,\n"
    "                'segment_index': seg_idx.get(sid),\n"
    "                'segment_id': sid,\n"
    "                'w_cost': round(seg_wc.get(sid, 0), 4),\n"
    "                'density': round(alloc.density, 4),\n"
    "                'norm_density': round(norm, 4),\n"
    "                'mnl_share_pct': round(share * 100, 2),\n"
    "                'effective_users_seg': round(eff_s, 4),\n"
    "                'unit_margin': round(margin, 2),\n"
    "                'profit_seg': round(eff_s * margin, 4),\n"
    "                'picks': ','.join(picks), 'price': price, 'delta': delta,\n"
    "            })\n"
    "\n"
    "    return pd.DataFrame(team_rows), pd.DataFrame(seg_rows)\n"
    "\n"
    "def run_scenario(name, rounds_spec, delta_schedule=None):\n"
    "    all_r, all_s = [], []\n"
    "    for i, rnd in enumerate(rounds_spec):\n"
    "        rno = rnd['round_no']\n"
    "        specs = [(t['name'], t['picks'], t['price']) for t in rnd['teams']]\n"
    "        av = rnd.get('alpha', 3.0); bv = rnd.get('beta', 3.0)\n"
    "        if delta_schedule is None:\n"
    "            d = rnd.get('delta', 0.1)\n"
    "        elif isinstance(delta_schedule, (int, float)):\n"
    "            d = float(delta_schedule)\n"
    "        else:\n"
    "            d = float(delta_schedule[i]) if i < len(delta_schedule) else float(delta_schedule[-1])\n"
    "        rdf, sdf = run_round(specs, alpha=av, beta=bv, delta=d)\n"
    "        rdf['round_no'] = rno; rdf['scenario'] = name\n"
    "        sdf['round_no'] = rno; sdf['scenario'] = name\n"
    "        all_r.append(rdf); all_s.append(sdf)\n"
    "    rdf_all = pd.concat(all_r, ignore_index=True)\n"
    "    rdf_all['cum_profit']  = rdf_all.groupby('team')['realized_profit'].cumsum()\n"
    "    rdf_all['cum_utility'] = rdf_all.groupby('team')['realized_utility'].cumsum()\n"
    "    return rdf_all, pd.concat(all_s, ignore_index=True)\n"
    "\n"
    "print('Helpers ready.')\n"
))

# ── Scenarios ──────────────────────────────────────────────────────────────

cells.append(md(
    "## Scenario 1 — Price War (same set [P], 6 rounds)\n"
    "All 3 teams start at price=100. B cuts to 85 in R3, A counters to 90 in R4, C goes premium."
))
cells.append(code(
    "S1 = [\n"
    "    {'round_no':1,'teams':[{'name':'TeamA','picks':['P'],'price':100},{'name':'TeamB','picks':['P'],'price':100},{'name':'TeamC','picks':['P'],'price':100}]},\n"
    "    {'round_no':2,'teams':[{'name':'TeamA','picks':['P'],'price':100},{'name':'TeamB','picks':['P'],'price':100},{'name':'TeamC','picks':['P'],'price':100}]},\n"
    "    {'round_no':3,'teams':[{'name':'TeamA','picks':['P'],'price':100},{'name':'TeamB','picks':['P'],'price':85}, {'name':'TeamC','picks':['P'],'price':100}]},\n"
    "    {'round_no':4,'teams':[{'name':'TeamA','picks':['P'],'price':90}, {'name':'TeamB','picks':['P'],'price':85}, {'name':'TeamC','picks':['P'],'price':100}]},\n"
    "    {'round_no':5,'teams':[{'name':'TeamA','picks':['P'],'price':90}, {'name':'TeamB','picks':['P'],'price':85}, {'name':'TeamC','picks':['P'],'price':108}]},\n"
    "    {'round_no':6,'teams':[{'name':'TeamA','picks':['P'],'price':90}, {'name':'TeamB','picks':['P'],'price':80}, {'name':'TeamC','picks':['P'],'price':108}]},\n"
    "]\n"
    "s1_r, s1_s = run_scenario('S1_PriceWar', S1)\n"
    "print(f'S1: {len(s1_r)} round rows, {len(s1_s)} segment rows')\n"
    "s1_r[['round_no','team','price','demand_share_pct','realized_profit','cum_profit']]\n"
))

cells.append(md(
    "## Scenario 2 — Selection Shock (8 rounds)\n"
    "TeamA starts [P], upgrades to [P,O,N] in R4. TeamB holds [P,N,I] throughout. TeamC copies A in R6."
))
cells.append(code(
    "S2 = [\n"
    "    {'round_no':1,'teams':[{'name':'TeamA','picks':['P'],         'price':100},{'name':'TeamB','picks':['P','N','I'],'price':95},{'name':'TeamC','picks':['P','O'],       'price':105}]},\n"
    "    {'round_no':2,'teams':[{'name':'TeamA','picks':['P'],         'price':100},{'name':'TeamB','picks':['P','N','I'],'price':95},{'name':'TeamC','picks':['P','O'],       'price':100}]},\n"
    "    {'round_no':3,'teams':[{'name':'TeamA','picks':['P'],         'price':100},{'name':'TeamB','picks':['P','N','I'],'price':90},{'name':'TeamC','picks':['P','O'],       'price':100}]},\n"
    "    {'round_no':4,'teams':[{'name':'TeamA','picks':['P','O','N'], 'price':100},{'name':'TeamB','picks':['P','N','I'],'price':90},{'name':'TeamC','picks':['P','O'],       'price':100}]},\n"
    "    {'round_no':5,'teams':[{'name':'TeamA','picks':['P','O','N'], 'price':95}, {'name':'TeamB','picks':['P','N','I'],'price':90},{'name':'TeamC','picks':['P','O'],       'price':95}]},\n"
    "    {'round_no':6,'teams':[{'name':'TeamA','picks':['P','O','N'], 'price':95}, {'name':'TeamB','picks':['P','N','I'],'price':85},{'name':'TeamC','picks':['P','O','N'],   'price':95}]},\n"
    "    {'round_no':7,'teams':[{'name':'TeamA','picks':['P','O','N'], 'price':90}, {'name':'TeamB','picks':['P','N','I'],'price':85},{'name':'TeamC','picks':['P','O','N'],   'price':90}]},\n"
    "    {'round_no':8,'teams':[{'name':'TeamA','picks':['P','O','N'], 'price':90}, {'name':'TeamB','picks':['P','N','I'],'price':85},{'name':'TeamC','picks':['P','O','N'],   'price':85}]},\n"
    "]\n"
    "s2_r, s2_s = run_scenario('S2_SelectionShock', S2)\n"
    "print(f'S2: {len(s2_r)} round rows')\n"
    "s2_r[['round_no','team','picks','price','demand_share_pct','realized_profit','cum_profit']]\n"
))

cells.append(md(
    "## Scenario 3 — Delta Sweep (6 rounds)\n"
    "Same teams and prices every round; **delta rises** each round: 0.02 → 0.05 → 0.10 → 0.20 → 0.35 → 0.50."
))
cells.append(code(
    "DELTA_SCHED = [0.02, 0.05, 0.10, 0.20, 0.35, 0.50]\n"
    "S3 = [\n"
    "    {'round_no': i+1, 'teams': [\n"
    "        {'name': 'TeamA [P]@100',    'picks': ['P'],         'price': 100},\n"
    "        {'name': 'TeamB [P,O,N]@95', 'picks': ['P','O','N'], 'price':  95},\n"
    "        {'name': 'TeamC [P,N,I]@90', 'picks': ['P','N','I'], 'price':  90},\n"
    "    ]} for i in range(6)\n"
    "]\n"
    "s3_r, s3_s = run_scenario('S3_DeltaSweep', S3, delta_schedule=DELTA_SCHED)\n"
    "print(f'S3: {len(s3_r)} round rows')\n"
    "s3_r[['round_no','team','price','delta','demand_share_pct','realized_profit']]\n"
))

cells.append(md(
    "## Scenario 4 — Full Tournament (4 teams, 8 rounds)\n"
    "Rounds 1-4: Beta(3,3) symmetric. Rounds 5-8: Beta(1.5,5) quality-preferring — "
    "env/social quality matters more, hitting [P,O,N] and [P,N,I] differently."
))
cells.append(code(
    "def make_s4_round(rno, prices):\n"
    "    teams_base = [\n"
    "        ('Alpha [P]',     ['P']),\n"
    "        ('Beta [P,O]',    ['P','O']),\n"
    "        ('Gamma [P,O,N]', ['P','O','N']),\n"
    "        ('Delta [P,N,I]', ['P','N','I']),\n"
    "    ]\n"
    "    return {\n"
    "        'round_no': rno,\n"
    "        'alpha': 3.0 if rno <= 4 else 1.5,\n"
    "        'beta':  3.0 if rno <= 4 else 5.0,\n"
    "        'teams': [{'name':n,'picks':p,'price':pr} for (n,p),pr in zip(teams_base,prices)]\n"
    "    }\n"
    "\n"
    "S4 = [\n"
    "    make_s4_round(1, [110,100, 95, 90]),\n"
    "    make_s4_round(2, [105,100, 95, 88]),\n"
    "    make_s4_round(3, [100,100, 95, 85]),\n"
    "    make_s4_round(4, [ 95, 98, 90, 85]),\n"
    "    make_s4_round(5, [ 95, 98, 90, 85]),\n"
    "    make_s4_round(6, [ 95, 95, 88, 82]),\n"
    "    make_s4_round(7, [ 92, 95, 88, 80]),\n"
    "    make_s4_round(8, [ 90, 92, 85, 80]),\n"
    "]\n"
    "\n"
    "def run_s4():\n"
    "    all_r, all_s = [], []\n"
    "    for rnd in S4:\n"
    "        rno = rnd['round_no']\n"
    "        specs = [(t['name'],t['picks'],t['price']) for t in rnd['teams']]\n"
    "        rdf, sdf = run_round(specs, alpha=rnd['alpha'], beta=rnd['beta'], delta=0.1)\n"
    "        rdf['round_no'] = rno; rdf['scenario'] = 'S4_Tournament'\n"
    "        rdf['beta_label'] = 'Bell(3,3)' if rno <= 4 else 'QualPref(1.5,5)'\n"
    "        sdf['round_no'] = rno; sdf['scenario'] = 'S4_Tournament'\n"
    "        all_r.append(rdf); all_s.append(sdf)\n"
    "    rdf_all = pd.concat(all_r, ignore_index=True)\n"
    "    rdf_all['cum_profit']  = rdf_all.groupby('team')['realized_profit'].cumsum()\n"
    "    rdf_all['cum_utility'] = rdf_all.groupby('team')['realized_utility'].cumsum()\n"
    "    return rdf_all, pd.concat(all_s, ignore_index=True)\n"
    "\n"
    "s4_r, s4_s = run_s4()\n"
    "print(f'S4: {len(s4_r)} round rows')\n"
    "s4_r[['round_no','team','picks','price','demand_share_pct','realized_profit','cum_profit','beta_label']]\n"
))

# ── Visualizations ─────────────────────────────────────────────────────────

cells.append(md("## Visualizations\n### Time-Series: Profit / Cumulative / Share / Price"))
cells.append(code(
    "def team_colors(teams):\n"
    "    return {t: PALETTE[i % len(PALETTE)] for i,t in enumerate(sorted(teams))}\n"
    "\n"
    "def plot_ts(df, title, figsize=(14,9)):\n"
    "    teams = sorted(df['team'].unique()); colors = team_colors(teams)\n"
    "    fig, axes = plt.subplots(2, 2, figsize=figsize)\n"
    "    fig.suptitle(title, fontsize=13, fontweight='bold')\n"
    "    specs_list = [\n"
    "        ('realized_profit',  'Profit / Round',       'o', '-'),\n"
    "        ('cum_profit',       'Cumulative Profit',    's', '-'),\n"
    "        ('demand_share_pct', 'Demand Share %',       '^', '-'),\n"
    "        ('price',            'Price',                'D', '--'),\n"
    "    ]\n"
    "    for ax, (col, ylabel, marker, ls) in zip(axes.flat, specs_list):\n"
    "        for team in teams:\n"
    "            td = df[df['team']==team].sort_values('round_no')\n"
    "            ax.plot(td['round_no'], td[col], marker=marker, label=team,\n"
    "                    color=colors[team], linewidth=2, linestyle=ls)\n"
    "        if col == 'demand_share_pct':\n"
    "            ax.axhline(100/len(teams), color='gray', linestyle=':', alpha=0.6,\n"
    "                       label=f'Equal ({100/len(teams):.1f}%)')\n"
    "        ax.set_title(ylabel); ax.set_xlabel('Round'); ax.set_ylabel(ylabel)\n"
    "        ax.legend(fontsize=7); ax.grid(alpha=0.3)\n"
    "        ax.xaxis.set_major_locator(plt.MaxNLocator(integer=True))\n"
    "    plt.tight_layout()\n"
    "    return fig\n"
    "\n"
    "fig1 = plot_ts(s1_r, 'S1 — Price War (same set [P], 6 rounds)')\n"
    "plt.savefig('s1_timeseries.png', dpi=120, bbox_inches='tight'); plt.show()\n"
    "\n"
    "fig2 = plot_ts(s2_r, 'S2 — Selection Shock (A upgrades R4, C copies R6)')\n"
    "plt.savefig('s2_timeseries.png', dpi=120, bbox_inches='tight'); plt.show()\n"
    "\n"
    "fig4 = plot_ts(s4_r, 'S4 — Tournament (4 teams, Beta shifts at R5)')\n"
    "for ax in fig4.get_axes():\n"
    "    ax.axvline(4.5, color='gray', linestyle=':', linewidth=1.5, alpha=0.7)\n"
    "plt.savefig('s4_timeseries.png', dpi=120, bbox_inches='tight'); plt.show()\n"
    "print('Time-series done.')\n"
))

cells.append(md("### Pie Charts — Demand Share by Round"))
cells.append(code(
    "def plot_pies(df, scenario_name, rounds=None):\n"
    "    if rounds is None: rounds = sorted(df['round_no'].unique())\n"
    "    n = len(rounds)\n"
    "    fig, axes = plt.subplots(1, n, figsize=(3*n, 3.5))\n"
    "    if n == 1: axes = [axes]\n"
    "    fig.suptitle(f'{scenario_name} — Demand Share', fontsize=11, fontweight='bold')\n"
    "    teams = sorted(df['team'].unique())\n"
    "    colors = [PALETTE[i%len(PALETTE)] for i in range(len(teams))]\n"
    "    wedge = {'edgecolor':'white','linewidth':1.5}\n"
    "    for ax, rno in zip(axes, rounds):\n"
    "        rd = df[df['round_no']==rno].sort_values('team')\n"
    "        shares = rd['demand_share_pct'].values\n"
    "        lbls = [t.split('[')[0].strip() or t for t in rd['team'].values]\n"
    "        ax.pie(shares, labels=lbls, colors=colors[:len(shares)], autopct='%1.1f%%',\n"
    "               startangle=90, wedgeprops=wedge, textprops={'fontsize':7})\n"
    "        ax.set_title(f'R{rno}', fontsize=9)\n"
    "    plt.tight_layout()\n"
    "    return fig\n"
    "\n"
    "plot_pies(s1_r, 'S1 Price War', [1,2,3,4,5,6])\n"
    "plt.savefig('s1_pies.png', dpi=110, bbox_inches='tight'); plt.show()\n"
    "\n"
    "plot_pies(s2_r, 'S2 Selection Shock', [1,3,4,6,8])\n"
    "plt.savefig('s2_pies.png', dpi=110, bbox_inches='tight'); plt.show()\n"
    "\n"
    "plot_pies(s4_r, 'S4 Tournament', [1,4,5,8])\n"
    "plt.savefig('s4_pies.png', dpi=110, bbox_inches='tight'); plt.show()\n"
    "print('Pies done.')\n"
))

cells.append(md("### Per-Segment Heatmaps (MNL share × segment, one round at a time)"))
cells.append(code(
    "def plot_seg_heatmap(sdf, rnd, title_sfx=''):\n"
    "    rd = sdf[sdf['round_no']==rnd].copy().sort_values('segment_index')\n"
    "    if rd.empty: return\n"
    "    teams = sorted(rd['team'].unique())\n"
    "    pivot = rd.pivot_table(index='segment_index', columns='team',\n"
    "                            values='mnl_share_pct', aggfunc='first')[teams]\n"
    "    fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(13, 5))\n"
    "    fig.suptitle(f'Round {rnd} — Per-Segment MNL Shares {title_sfx}',\n"
    "                 fontsize=12, fontweight='bold')\n"
    "    # heatmap\n"
    "    im = ax1.imshow(pivot.values, aspect='auto', cmap='YlOrRd', vmin=0, vmax=100)\n"
    "    ax1.set_xticks(range(len(teams)))\n"
    "    ax1.set_xticklabels(teams, rotation=20, ha='right', fontsize=8)\n"
    "    ax1.set_yticks(range(len(pivot)))\n"
    "    ax1.set_yticklabels([f'Seg {i}' for i in pivot.index], fontsize=7)\n"
    "    ax1.set_title('MNL Share % per Segment')\n"
    "    plt.colorbar(im, ax=ax1, label='Share %')\n"
    "    # stacked bar\n"
    "    wcosts = rd.drop_duplicates('segment_index').sort_values('segment_index')['w_cost'].values\n"
    "    bottom = np.zeros(len(pivot))\n"
    "    for j, team in enumerate(teams):\n"
    "        vals = pivot[team].fillna(0).values\n"
    "        ax2.barh(range(len(pivot)), vals, left=bottom,\n"
    "                 label=team, color=PALETTE[j%len(PALETTE)], alpha=0.85)\n"
    "        bottom += vals\n"
    "    ax2.set_yticks(range(len(pivot)))\n"
    "    ax2.set_yticklabels([f'Seg {i}  wc={wc:.2f}' for i,wc in zip(pivot.index,wcosts)], fontsize=7)\n"
    "    ax2.set_xlabel('Share %')\n"
    "    ax2.set_title('Stacked Share (low w_cost -> high w_cost)')\n"
    "    ax2.legend(fontsize=7, loc='lower right'); ax2.set_xlim(0,100)\n"
    "    plt.tight_layout()\n"
    "    return fig\n"
    "\n"
    "# S1: before, during, after price war\n"
    "for rno in [1, 3, 6]:\n"
    "    plot_seg_heatmap(s1_s, rno, '(S1 Price War)')\n"
    "    plt.savefig(f's1_seg_r{rno}.png', dpi=100, bbox_inches='tight'); plt.show()\n"
    "\n"
    "# S2: just before and just after selection upgrade\n"
    "for rno in [3, 4, 8]:\n"
    "    plot_seg_heatmap(s2_s, rno, '(S2 Selection Shock)')\n"
    "    plt.savefig(f's2_seg_r{rno}.png', dpi=100, bbox_inches='tight'); plt.show()\n"
    "\n"
    "# S4: last Bell round vs first QualPref round\n"
    "for rno in [4, 5]:\n"
    "    plot_seg_heatmap(s4_s, rno, '(S4 Beta Shift)')\n"
    "    plt.savefig(f's4_seg_r{rno}.png', dpi=100, bbox_inches='tight'); plt.show()\n"
    "print('Heatmaps done.')\n"
))

cells.append(md("### Delta Sweep — Price Sensitivity Chart"))
cells.append(code(
    "fig_d, axes = plt.subplots(1, 2, figsize=(12, 5))\n"
    "fig_d.suptitle('S3 — Delta Sweep: effect of rising price sensitivity',\n"
    "               fontsize=12, fontweight='bold')\n"
    "teams = sorted(s3_r['team'].unique()); colors = team_colors(teams)\n"
    "for team in teams:\n"
    "    td = s3_r[s3_r['team']==team].sort_values('delta')\n"
    "    axes[0].plot(td['delta'], td['demand_share_pct'], marker='o',\n"
    "                 label=team, color=colors[team], linewidth=2)\n"
    "    axes[1].plot(td['delta'], td['realized_profit'], marker='s',\n"
    "                 label=team, color=colors[team], linewidth=2)\n"
    "for ax, title, ylabel in zip(axes,\n"
    "    ['Demand Share % vs delta','Realized Profit vs delta'],\n"
    "    ['Share %','Profit']):\n"
    "    ax.set_title(title); ax.set_xlabel('delta (log scale)')\n"
    "    ax.set_ylabel(ylabel); ax.set_xscale('log')\n"
    "    ax.legend(fontsize=8); ax.grid(alpha=0.3)\n"
    "plt.tight_layout()\n"
    "plt.savefig('s3_delta.png', dpi=120, bbox_inches='tight'); plt.show()\n"
    "print('Delta chart done.')\n"
))

cells.append(md("### Utility Time-Series — All Scenarios"))
cells.append(code(
    "fig_u, axes = plt.subplots(2, 2, figsize=(14,9))\n"
    "fig_u.suptitle('Realized Utility per Round — All Scenarios', fontsize=13, fontweight='bold')\n"
    "for ax, (df, label, xcol) in zip(axes.flat, [\n"
    "    (s1_r,'S1 Price War',       'round_no'),\n"
    "    (s2_r,'S2 Selection Shock', 'round_no'),\n"
    "    (s3_r,'S3 Delta Sweep',     'delta'),\n"
    "    (s4_r,'S4 Tournament',      'round_no'),\n"
    "]):\n"
    "    teams = sorted(df['team'].unique()); colors = team_colors(teams)\n"
    "    for team in teams:\n"
    "        td = df[df['team']==team].sort_values(xcol)\n"
    "        ax.plot(td[xcol], td['realized_utility'], marker='o',\n"
    "                label=team, color=colors[team], linewidth=2)\n"
    "    ax.set_title(label); ax.set_xlabel(xcol); ax.set_ylabel('Utility')\n"
    "    if xcol == 'delta': ax.set_xscale('log')\n"
    "    ax.legend(fontsize=6); ax.grid(alpha=0.3)\n"
    "    ax.xaxis.set_major_locator(plt.MaxNLocator(integer=True))\n"
    "plt.tight_layout()\n"
    "plt.savefig('all_utility.png', dpi=120, bbox_inches='tight'); plt.show()\n"
    "print('Utility charts done.')\n"
))

# ── Excel Export ──────────────────────────────────────────────────────────

cells.append(md("## Export to Excel"))
cells.append(code(
    "OUTPUT = Path('round_simulation_results.xlsx')\n"
    "\n"
    "def profit_pivot(df):\n"
    "    return df.pivot_table(index='team', columns='round_no',\n"
    "                          values='realized_profit', aggfunc='first').round(1)\n"
    "def cum_pivot(df):\n"
    "    return df.pivot_table(index='team', columns='round_no',\n"
    "                          values='cum_profit', aggfunc='last').round(1)\n"
    "def share_pivot(df):\n"
    "    return df.pivot_table(index='team', columns='round_no',\n"
    "                          values='demand_share_pct', aggfunc='first').round(2)\n"
    "def utility_pivot(df):\n"
    "    return df.pivot_table(index='team', columns='round_no',\n"
    "                          values='realized_utility', aggfunc='first').round(3)\n"
    "def seg_avg(sdf):\n"
    "    return sdf.groupby(['segment_index','team'])['mnl_share_pct'].mean().unstack().round(2)\n"
    "def seg_rnd(sdf, rno):\n"
    "    return sdf[sdf['round_no']==rno].pivot_table(\n"
    "        index='segment_index', columns='team',\n"
    "        values='mnl_share_pct', aggfunc='first').round(2)\n"
    "\n"
    "with pd.ExcelWriter(OUTPUT, engine='openpyxl') as w:\n"
    "    # Raw data\n"
    "    s1_r.to_excel(w, sheet_name='S1_Rounds',      index=False)\n"
    "    s1_s.to_excel(w, sheet_name='S1_Segments',    index=False)\n"
    "    s2_r.to_excel(w, sheet_name='S2_Rounds',      index=False)\n"
    "    s2_s.to_excel(w, sheet_name='S2_Segments',    index=False)\n"
    "    s3_r.to_excel(w, sheet_name='S3_Rounds',      index=False)\n"
    "    s3_s.to_excel(w, sheet_name='S3_Segments',    index=False)\n"
    "    s4_r.to_excel(w, sheet_name='S4_Rounds',      index=False)\n"
    "    s4_s.to_excel(w, sheet_name='S4_Segments',    index=False)\n"
    "    # Pivots\n"
    "    profit_pivot(s1_r).to_excel(w,  sheet_name='S1_Profit_Pivot')\n"
    "    cum_pivot(s1_r).to_excel(w,     sheet_name='S1_CumProfit_Pivot')\n"
    "    share_pivot(s1_r).to_excel(w,   sheet_name='S1_Share_Pivot')\n"
    "    utility_pivot(s1_r).to_excel(w, sheet_name='S1_Utility_Pivot')\n"
    "    profit_pivot(s2_r).to_excel(w,  sheet_name='S2_Profit_Pivot')\n"
    "    cum_pivot(s2_r).to_excel(w,     sheet_name='S2_CumProfit_Pivot')\n"
    "    share_pivot(s2_r).to_excel(w,   sheet_name='S2_Share_Pivot')\n"
    "    profit_pivot(s4_r).to_excel(w,  sheet_name='S4_Profit_Pivot')\n"
    "    cum_pivot(s4_r).to_excel(w,     sheet_name='S4_CumProfit_Pivot')\n"
    "    share_pivot(s4_r).to_excel(w,   sheet_name='S4_Share_Pivot')\n"
    "    # Segment breakdowns\n"
    "    seg_avg(s1_s).to_excel(w,      sheet_name='S1_SegShare_AllRnd_Avg')\n"
    "    seg_avg(s2_s).to_excel(w,      sheet_name='S2_SegShare_AllRnd_Avg')\n"
    "    seg_avg(s4_s).to_excel(w,      sheet_name='S4_SegShare_AllRnd_Avg')\n"
    "    seg_rnd(s1_s,1).to_excel(w,   sheet_name='S1_Seg_R1_Baseline')\n"
    "    seg_rnd(s1_s,3).to_excel(w,   sheet_name='S1_Seg_R3_PriceCut')\n"
    "    seg_rnd(s1_s,6).to_excel(w,   sheet_name='S1_Seg_R6_Final')\n"
    "    seg_rnd(s2_s,3).to_excel(w,   sheet_name='S2_Seg_R3_BeforeUpgrade')\n"
    "    seg_rnd(s2_s,4).to_excel(w,   sheet_name='S2_Seg_R4_AfterUpgrade')\n"
    "    seg_rnd(s4_s,4).to_excel(w,   sheet_name='S4_Seg_R4_Bell')\n"
    "    seg_rnd(s4_s,5).to_excel(w,   sheet_name='S4_Seg_R5_QualPref')\n"
    "\n"
    "print(f'Saved -> {OUTPUT.resolve()}')\n"
    "print(f'Total raw rows: {sum(len(d) for d in [s1_r,s1_s,s2_r,s2_s,s3_r,s3_s,s4_r,s4_s])}')\n"
))

cells.append(md("## Summary"))
cells.append(code(
    "print('='*65)\n"
    "print('SIMULATION SUMMARY')\n"
    "print('='*65)\n"
    "for label, df in [('S1 Price War',s1_r),('S2 Selection Shock',s2_r),\n"
    "                   ('S3 Delta Sweep',s3_r),('S4 Tournament',s4_r)]:\n"
    "    final = df.groupby('team')['realized_profit'].sum().sort_values(ascending=False)\n"
    "    print(f'\n{label} - Total Profit Ranking:')\n"
    "    for team, profit in final.items():\n"
    "        avg_share = df[df['team']==team]['demand_share_pct'].mean()\n"
    "        print(f'  {team:<38s} profit={profit:7.0f}  avg_share={avg_share:.1f}%')\n"
    "\n"
    "print('\nS3 - Price leader (lowest price [P,N,I]@90) vs delta:')\n"
    "tc = s3_r[s3_r['team'].str.contains('90')].sort_values('round_no')\n"
    "for _, row in tc.iterrows():\n"
    "    print(f'  delta={row[\"delta\"]:.2f}  share={row[\"demand_share_pct\"]:.1f}%  profit={row[\"realized_profit\"]:.0f}')\n"
))

nb = {
    "nbformat": 4, "nbformat_minor": 5,
    "metadata": {
        "kernelspec": {"display_name":"Python 3","language":"python","name":"python3"},
        "language_info": {"name":"python","version":"3.11.0"}
    },
    "cells": cells
}

out = Path(__file__).parent / "round_simulation.ipynb"
with open(out, "w", encoding="utf-8") as f:
    json.dump(nb, f, indent=1, ensure_ascii=False)
print(f"Written: {out}  |  Cells: {len(cells)}")
