export const state = {
  objective: "max_profit",
  role: null,
  gameCode: "",
  gameName: "",
  suppliers: [],
  selected: new Set(),
  config: null,
  sortBy: "profit",
  feasibleOnly: false,
  latestRows: [],
  plotX: "profit",
  plotY: "utility",
  roundNo: null,
  totalRounds: null,
  roundEndsAt: null,
  roundTimerId: null,
  roundSyncId: null,
  betaAlpha: 3.0,
  betaBeta: 3.0,
  delta: 0.1,
  numSegments: 0,
  historyMetric: "profit",
};

export const LOBBY_STORAGE_KEY = "arya_lobby_state_v1";
export const ROUND_SYNC_INTERVAL_MS = 2000;

export const PLOT_COLUMNS = {
  profit: "Profit",
  utility: "Utility",
  env_avg: "Avg Env",
  social_avg: "Avg Social",
  cost_avg: "Avg Cost",
  strategic_avg: "Avg Strategic",
  improvement_avg: "Avg Improvement",
  low_quality_avg: "Avg Low Quality",
  num_suppliers: "# Suppliers",
};

export const el = {
  supplierList: document.getElementById("supplierList"),
  manualMetrics: document.getElementById("manualMetrics"),
  statusText: document.getElementById("statusText"),
  configInfo: document.getElementById("configInfo"),
  benchmarkProfitPanel: document.getElementById("benchmarkProfitPanel"),
  benchmarkUtilPanel: document.getElementById("benchmarkUtilPanel"),
  teamName: document.getElementById("teamName"),
  playerName: document.getElementById("playerName"),
  pricePerUser: document.getElementById("pricePerUser"),
  leaderboardBody: document.querySelector("#leaderboardTable tbody"),
  sortSelect: document.getElementById("sortSelect"),
  feasibleOnly: document.getElementById("feasibleOnly"),
  plotXSelect: document.getElementById("plotXSelect"),
  plotYSelect: document.getElementById("plotYSelect"),
  leaderboardScatter: document.getElementById("leaderboardScatter"),
  lobbyScreen: document.getElementById("lobbyScreen"),
  gameScreen: document.getElementById("gameScreen"),
  sessionSummary: document.getElementById("sessionSummary"),
  adminGameName: document.getElementById("adminGameName"),
  adminName: document.getElementById("adminName"),
  adminNumberOfRounds: document.getElementById("adminNumberOfRounds"),
  btnEnterAdmin: document.getElementById("btnEnterAdmin"),
  adminHint: document.getElementById("adminHint"),
  playerJoinCode: document.getElementById("playerJoinCode"),
  playerTeamName: document.getElementById("playerTeamName"),
  btnEnterPlayer: document.getElementById("btnEnterPlayer"),
  playerHint: document.getElementById("playerHint"),
  btnBackLobby: document.getElementById("btnBackLobby"),
  roundSummary: document.getElementById("roundSummary"),
  adminControls: document.getElementById("adminControls"),
  roundTimerSeconds: document.getElementById("roundTimerSeconds"),
  betaAlpha: document.getElementById("betaAlpha"),
  betaBeta: document.getElementById("betaBeta"),
  deltaInput: document.getElementById("deltaInput"),
  btnStartRound: document.getElementById("btnStartRound"),
  btnRunMatch: document.getElementById("btnRunMatch"),
  btnApplyDistribution: document.getElementById("btnApplyDistribution"),
  adminRoundHint: document.getElementById("adminRoundHint"),
  matchingResultCard: document.getElementById("matchingResultCard"),
  matchingResultText: document.getElementById("matchingResultText"),
  matchingTableBody: document.querySelector("#matchingTable tbody"),
  segmentSharesDetails: document.getElementById("segmentSharesDetails"),
  segmentSharesHead: document.getElementById("segmentSharesHead"),
  segmentSharesBody: document.getElementById("segmentSharesBody"),
  distributionChart: document.getElementById("distributionChart"),
  btnBackToSelection: document.getElementById("btnBackToSelection"),
  historyMetricSelect: document.getElementById("historyMetricSelect"),
};
