export const state = {
  objective: "max_profit",
  role: null,
  adminPlays: false,
  gameCode: "",
  gameName: "",
  suppliers: [],
  selected: {}, // { [category]: supplier_id } — one entry per category
  config: null,
  latestRows: [],
  plotX: "avg_realized_utility",
  plotY: "avg_market_share_pct",
  roundNo: null,
  totalRounds: null,
  roundEndsAt: null,
  roundTimerId: null,
  roundSyncId: null,
  betaAlpha: 3.0,
  betaBeta: 3.0,
  delta: 0.1,
  qualitySensitivity: 1.0,
  auditProbability: 0.0,
  catchProbability: 1.0,
  numSegments: 0,
};

export const LOBBY_STORAGE_KEY = "arya_lobby_state_v1";
export const ROUND_SYNC_INTERVAL_MS = 2000;

export const PLOT_COLUMNS = {
  avg_realized_utility:  "Avg Market Utility",
  avg_buyer_utility:     "Avg Buyer Utility",
  avg_profit:            "Avg Profit",
  avg_market_share_pct:  "Avg Demand Share %",
};

export const el = {
  supplierList: document.getElementById("supplierList"),
  manualMetrics: document.getElementById("manualMetrics"),
  statusText: document.getElementById("statusText"),
  configInfo: document.getElementById("configInfo"),
  benchmarkProfitPanel: document.getElementById("benchmarkProfitPanel"),
  benchmarkUtilPanel: document.getElementById("benchmarkUtilPanel"),
  teamName: document.getElementById("teamName"),
  playerName: null,
  pricePerUser: document.getElementById("pricePerUser"),
  btnManual: document.getElementById("btnManual"),
  btnSubmit: document.getElementById("btnSubmit"),
  leaderboardBody: document.querySelector("#leaderboardTable tbody"),
  turnLeaderboardBody: document.querySelector("#turnLeaderboardTable tbody"),
  cumulativeMatchBody: document.querySelector("#cumulativeMatchTable tbody"),
  plotXSelect: document.getElementById("plotXSelect"),
  plotYSelect: document.getElementById("plotYSelect"),
  leaderboardScatter: document.getElementById("leaderboardScatter"),
  lobbyScreen: document.getElementById("lobbyScreen"),
  gameScreen: document.getElementById("gameScreen"),
  gameMainGrid: document.getElementById("gameMainGrid"),
  adminObserverCard: document.getElementById("adminObserverCard"),
  sessionSummary: document.getElementById("sessionSummary"),
  adminGameName: document.getElementById("adminGameName"),
  adminName: document.getElementById("adminName"),
  adminNumberOfRounds: document.getElementById("adminNumberOfRounds"),
  btnEnterAdmin: document.getElementById("btnEnterAdmin"),
  adminHint: document.getElementById("adminHint"),
  playerJoinCode: document.getElementById("playerJoinCode"),
  playerTeamName: document.getElementById("playerTeamName"),
  btnEnterPlayer: document.getElementById("btnEnterPlayer"),
  playerHint: document.getElementById("playerHint"),
  btnBackLobby: document.getElementById("btnBackLobby"),
  roundSummary: document.getElementById("roundSummary"),
  adminControls: document.getElementById("adminControls"),
  roundTimerSeconds: document.getElementById("roundTimerSeconds"),
  betaAlpha: document.getElementById("betaAlpha"),
  betaBeta: document.getElementById("betaBeta"),
  deltaInput: document.getElementById("deltaInput"),
  qualitySensitivityInput: document.getElementById("qualitySensitivityInput"),
  auditProbabilityInput: document.getElementById("auditProbabilityInput"),
  catchProbabilityInput: document.getElementById("catchProbabilityInput"),
  btnStartRound: document.getElementById("btnStartRound"),
  btnRunMatch: document.getElementById("btnRunMatch"),
  btnApplyDistribution: document.getElementById("btnApplyDistribution"),
  adminPlayToggle: document.getElementById("adminPlayToggle"),
  adminRoundHint: document.getElementById("adminRoundHint"),
  matchingResultCard: document.getElementById("matchingResultCard"),
  matchingResultText: document.getElementById("matchingResultText"),
  matchingTableBody: document.querySelector("#matchingTable tbody"),
  segmentSharesDetails: document.getElementById("segmentSharesDetails"),
  segmentSharesHead: document.getElementById("segmentSharesHead"),
  segmentSharesBody: document.getElementById("segmentSharesBody"),
  distributionChart: document.getElementById("distributionChart"),
  btnBackToSelection: document.getElementById("btnBackToSelection"),
};
