export const state = {
  objective: "max_profit",
  role: null,
  gameCode: "",
  gameName: "",
  suppliers: [],
  selected: {}, // { [category]: supplier_id } — one entry per category
  config: null,
  latestRows: [],
  plotX: "supplier_utility",
  plotY: "market_share_pct",
  roundNo: null,
  totalRounds: null,
  roundEndsAt: null,
  roundTimerId: null,
  roundSyncId: null,
  betaAlpha: 3.0,
  betaBeta: 3.0,
  delta: 0.1,
  auditProbability: 0.0,
  catchProbability: 1.0,
  numSegments: 0,
  historyMetric: "profit",
};

export const LOBBY_STORAGE_KEY = "arya_lobby_state_v1";
export const ROUND_SYNC_INTERVAL_MS = 2000;

export const PLOT_COLUMNS = {
  supplier_utility: "Supplier Utility",
  market_share_pct: "Market Share %",
  supplier_quality: "Supplier Quality",
  profit_cost_score: "Profit Cost Score",
  realized_profit: "Profit",
  realized_utility: "Realized Utility",
  total_supplier_utility: "Cumulative Supplier Utility",
  total_market_share_pct: "Cumulative Market Share %",
  total_supplier_quality: "Cumulative Supplier Quality",
  total_profit: "Cumulative Profit",
};

export const el = {
  supplierList: document.getElementById("supplierList"),
  manualMetrics: document.getElementById("manualMetrics"),
  statusText: document.getElementById("statusText"),
  configInfo: document.getElementById("configInfo"),
  benchmarkProfitPanel: document.getElementById("benchmarkProfitPanel"),
  benchmarkUtilPanel: document.getElementById("benchmarkUtilPanel"),
  teamName: document.getElementById("teamName"),
  playerName: document.getElementById("playerName"),
  pricePerUser: document.getElementById("pricePerUser"),
  leaderboardBody: document.querySelector("#leaderboardTable tbody"),
  turnLeaderboardBody: document.querySelector("#turnLeaderboardTable tbody"),
  plotXSelect: document.getElementById("plotXSelect"),
  plotYSelect: document.getElementById("plotYSelect"),
  leaderboardScatter: document.getElementById("leaderboardScatter"),
  lobbyScreen: document.getElementById("lobbyScreen"),
  gameScreen: document.getElementById("gameScreen"),
  sessionSummary: document.getElementById("sessionSummary"),
  adminGameName: document.getElementById("adminGameName"),
  adminName: document.getElementById("adminName"),
  adminNumberOfRounds: document.getElementById("adminNumberOfRounds"),
  btnEnterAdmin: document.getElementById("btnEnterAdmin"),
  adminHint: document.getElementById("adminHint"),
  playerJoinCode: document.getElementById("playerJoinCode"),
  playerTeamName: document.getElementById("playerTeamName"),
  btnEnterPlayer: document.getElementById("btnEnterPlayer"),
  playerHint: document.getElementById("playerHint"),
  btnBackLobby: document.getElementById("btnBackLobby"),
  roundSummary: document.getElementById("roundSummary"),
  adminControls: document.getElementById("adminControls"),
  roundTimerSeconds: document.getElementById("roundTimerSeconds"),
  betaAlpha: document.getElementById("betaAlpha"),
  betaBeta: document.getElementById("betaBeta"),
  deltaInput: document.getElementById("deltaInput"),
  auditProbabilityInput: document.getElementById("auditProbabilityInput"),
  catchProbabilityInput: document.getElementById("catchProbabilityInput"),
  btnStartRound: document.getElementById("btnStartRound"),
  btnRunMatch: document.getElementById("btnRunMatch"),
  btnApplyDistribution: document.getElementById("btnApplyDistribution"),
  adminRoundHint: document.getElementById("adminRoundHint"),
  matchingResultCard: document.getElementById("matchingResultCard"),
  matchingResultText: document.getElementById("matchingResultText"),
  matchingTableBody: document.querySelector("#matchingTable tbody"),
  segmentSharesDetails: document.getElementById("segmentSharesDetails"),
  segmentSharesHead: document.getElementById("segmentSharesHead"),
  segmentSharesBody: document.getElementById("segmentSharesBody"),
  distributionChart: document.getElementById("distributionChart"),
  btnBackToSelection: document.getElementById("btnBackToSelection"),
  historyMetricSelect: document.getElementById("historyMetricSelect"),
};
